//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: smartlight.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Smartlight_LightClient`, then call methods of this protocol to make API calls.
public protocol Smartlight_LightClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Smartlight_LightClientInterceptorFactoryProtocol? { get }

  func getIsOn(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions?
  ) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, SwiftProtobuf.Google_Protobuf_BoolValue>

  func setIsOn(
    _ request: SwiftProtobuf.Google_Protobuf_BoolValue,
    callOptions: CallOptions?
  ) -> UnaryCall<SwiftProtobuf.Google_Protobuf_BoolValue, SwiftProtobuf.Google_Protobuf_Empty>
}

extension Smartlight_LightClientProtocol {
  public var serviceName: String {
    return "smartlight.Light"
  }

  /// Unary call to GetIsOn
  ///
  /// - Parameters:
  ///   - request: Request to send to GetIsOn.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getIsOn(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, SwiftProtobuf.Google_Protobuf_BoolValue> {
    return self.makeUnaryCall(
      path: "/smartlight.Light/GetIsOn",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetIsOnInterceptors() ?? []
    )
  }

  /// Unary call to SetIsOn
  ///
  /// - Parameters:
  ///   - request: Request to send to SetIsOn.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func setIsOn(
    _ request: SwiftProtobuf.Google_Protobuf_BoolValue,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<SwiftProtobuf.Google_Protobuf_BoolValue, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: "/smartlight.Light/SetIsOn",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetIsOnInterceptors() ?? []
    )
  }
}

public protocol Smartlight_LightClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'getIsOn'.
  func makeGetIsOnInterceptors() -> [ClientInterceptor<SwiftProtobuf.Google_Protobuf_Empty, SwiftProtobuf.Google_Protobuf_BoolValue>]

  /// - Returns: Interceptors to use when invoking 'setIsOn'.
  func makeSetIsOnInterceptors() -> [ClientInterceptor<SwiftProtobuf.Google_Protobuf_BoolValue, SwiftProtobuf.Google_Protobuf_Empty>]
}

public final class Smartlight_LightClient: Smartlight_LightClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Smartlight_LightClientInterceptorFactoryProtocol?

  /// Creates a client for the smartlight.Light service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Smartlight_LightClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

